var AttendeeActions = Reflux.createActions([
    'fetchInternal',
    'fetchExternal',
    'selectExternalAttendee',
    'unselectExternalAttendee',
    'selectInternalAttendee',
    'unselectInternalAttendee',
    'searchInternal',
    'searchExternal',
    'eventCreated',
    'tabChanged',
    'roleFilterChosen',
    'removeFilters',
    'filterInternal',
    'filterExternal',
    'createAttendee',
    'editAttendees',
    'canSelectAttendees',
    'updateAreYouAttending',
    'showAttendeesList',
    'unselectAttendee',
    'domainValidate',
    'topicChange',
    'resetAttendeeList',
    'resetParticipantList',
    'sessionChange',
    'clearAttendees',
    'selectMappingAttendees',
    'sessionEditSelectAttendees',
    'canSelectSessionUsers',
    'addAttendeeData'
]);

module.exports = AttendeeActions;