# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11eeb6b98b7224e42b4b45667bcf87d0b4c68ff8f9fc86831856736b4a1f66606dea82c5bbc2f026dde33efb09b33e96d600b28fca1ad973f057305c2557575f

test:
  secret_key_base: 4883a0881ba0d72becb82b6e381e6cd034f3878c4a6ec508c2f667de48a118f42aa8c8f42d09786503b04a2a551120b9cb90d644db49d970031a7343f244977b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
